### ISSUE TITLE
what the shape of 'graph_len'?

### ISSUE THREAD

**Issue by jiaruHithub** [Starlien95/GraphPrompt#2]
Hi, thanks for the released code: 
 Could you tell me what is the shape of ```graph_len``` and ```embedding```? Like in https://github.com/Starlien95/GraphPrompt/blob/c66fee2d3359bb23a4f759e6feb0618a470d9ce8/graphdownstream/prompt_fewshot.py#L200
and
https://github.com/Starlien95/GraphPrompt/blob/c66fee2d3359bb23a4f759e6feb0618a470d9ce8/graphdownstream/prompt_fewshot.py#L212

and what they represent?
Thanks for reply!

**Comment by Starlien95** [comment]
The code for this project inherits from my previous work, so there are some redundant parts. For example, "graph_len" is actually unnecessary and was only kept because it was part of the previous code framework.

1."graph_len" is used to separate each graph in the batch by recording the number of nodes in each graph.
2."embedding" represents the embedding of each node.

You can print their sizes to see their shapes.

**Comment by jiaruHithub** [comment]
Thanks!
When using ```graph_prompt_layer_sum```, are there no parameters involved in the training?
I found that using the ```self.weight= torch.nn.Parameter(torch.Tensor(2, 2))```, but those parameters not be involved with any other tensor about input or template.

Thanks!
